/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiturgiaIndexRouteImport } from './routes/liturgia.index'
import { Route as HinoLanguageNumberRouteImport } from './routes/hino.$language.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiturgiaIndexRoute = LiturgiaIndexRouteImport.update({
  id: '/liturgia/',
  path: '/liturgia/',
  getParentRoute: () => rootRouteImport,
} as any)
const HinoLanguageNumberRoute = HinoLanguageNumberRouteImport.update({
  id: '/hino/$language/$number',
  path: '/hino/$language/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liturgia/': typeof LiturgiaIndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liturgia': typeof LiturgiaIndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liturgia/': typeof LiturgiaIndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liturgia/' | '/hino/$language/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liturgia' | '/hino/$language/$number'
  id: '__root__' | '/' | '/liturgia/' | '/hino/$language/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiturgiaIndexRoute: typeof LiturgiaIndexRoute
  HinoLanguageNumberRoute: typeof HinoLanguageNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liturgia/': {
      id: '/liturgia/'
      path: '/liturgia'
      fullPath: '/liturgia/'
      preLoaderRoute: typeof LiturgiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hino/$language/$number': {
      id: '/hino/$language/$number'
      path: '/hino/$language/$number'
      fullPath: '/hino/$language/$number'
      preLoaderRoute: typeof HinoLanguageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiturgiaIndexRoute: LiturgiaIndexRoute,
  HinoLanguageNumberRoute: HinoLanguageNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
