/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetorLanguageNumberRouteImport } from './routes/projetor.$language.$number'
import { Route as HinoLanguageNumberRouteImport } from './routes/hino.$language.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetorLanguageNumberRoute = ProjetorLanguageNumberRouteImport.update({
  id: '/projetor/$language/$number',
  path: '/projetor/$language/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const HinoLanguageNumberRoute = HinoLanguageNumberRouteImport.update({
  id: '/hino/$language/$number',
  path: '/hino/$language/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
  '/projetor/$language/$number': typeof ProjetorLanguageNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
  '/projetor/$language/$number': typeof ProjetorLanguageNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
  '/projetor/$language/$number': typeof ProjetorLanguageNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hino/$language/$number' | '/projetor/$language/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hino/$language/$number' | '/projetor/$language/$number'
  id:
    | '__root__'
    | '/'
    | '/hino/$language/$number'
    | '/projetor/$language/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HinoLanguageNumberRoute: typeof HinoLanguageNumberRoute
  ProjetorLanguageNumberRoute: typeof ProjetorLanguageNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetor/$language/$number': {
      id: '/projetor/$language/$number'
      path: '/projetor/$language/$number'
      fullPath: '/projetor/$language/$number'
      preLoaderRoute: typeof ProjetorLanguageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hino/$language/$number': {
      id: '/hino/$language/$number'
      path: '/hino/$language/$number'
      fullPath: '/hino/$language/$number'
      preLoaderRoute: typeof HinoLanguageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HinoLanguageNumberRoute: HinoLanguageNumberRoute,
  ProjetorLanguageNumberRoute: ProjetorLanguageNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
