/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiturgiaIndexRouteImport } from './routes/liturgia.index'
import { Route as LiturgiaIdRouteImport } from './routes/liturgia.$id'
import { Route as HinoLanguageNumberRouteImport } from './routes/hino.$language.$number'
import { Route as PartilharLanguageNumberRouteImport } from './routes/partilhar.$language.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiturgiaIndexRoute = LiturgiaIndexRouteImport.update({
  id: '/liturgia/',
  path: '/liturgia/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiturgiaIdRoute = LiturgiaIdRouteImport.update({
  id: '/liturgia/$id',
  path: '/liturgia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HinoLanguageNumberRoute = HinoLanguageNumberRouteImport.update({
  id: '/hino/$language/$number',
  path: '/hino/$language/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const PartilharLanguageNumberRoute = PartilharLanguageNumberRouteImport.update({
  id: '/partilhar/$language/$number',
  path: '/partilhar/$language/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liturgia/$id': typeof LiturgiaIdRoute
  '/liturgia/': typeof LiturgiaIndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
  '/partilhar/$language/$number': typeof PartilharLanguageNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liturgia/$id': typeof LiturgiaIdRoute
  '/liturgia': typeof LiturgiaIndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
  '/partilhar/$language/$number': typeof PartilharLanguageNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liturgia/$id': typeof LiturgiaIdRoute
  '/liturgia/': typeof LiturgiaIndexRoute
  '/hino/$language/$number': typeof HinoLanguageNumberRoute
  '/partilhar/$language/$number': typeof PartilharLanguageNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/liturgia/$id'
    | '/liturgia/'
    | '/hino/$language/$number'
    | '/partilhar/$language/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/liturgia/$id'
    | '/liturgia'
    | '/hino/$language/$number'
    | '/partilhar/$language/$number'
  id:
    | '__root__'
    | '/'
    | '/liturgia/$id'
    | '/liturgia/'
    | '/hino/$language/$number'
    | '/partilhar/$language/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiturgiaIdRoute: typeof LiturgiaIdRoute
  LiturgiaIndexRoute: typeof LiturgiaIndexRoute
  HinoLanguageNumberRoute: typeof HinoLanguageNumberRoute
  PartilharLanguageNumberRoute: typeof PartilharLanguageNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liturgia/': {
      id: '/liturgia/'
      path: '/liturgia'
      fullPath: '/liturgia/'
      preLoaderRoute: typeof LiturgiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liturgia/$id': {
      id: '/liturgia/$id'
      path: '/liturgia/$id'
      fullPath: '/liturgia/$id'
      preLoaderRoute: typeof LiturgiaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hino/$language/$number': {
      id: '/hino/$language/$number'
      path: '/hino/$language/$number'
      fullPath: '/hino/$language/$number'
      preLoaderRoute: typeof HinoLanguageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partilhar/$language/$number': {
      id: '/partilhar/$language/$number'
      path: '/partilhar/$language/$number'
      fullPath: '/partilhar/$language/$number'
      preLoaderRoute: typeof PartilharLanguageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiturgiaIdRoute: LiturgiaIdRoute,
  LiturgiaIndexRoute: LiturgiaIndexRoute,
  HinoLanguageNumberRoute: HinoLanguageNumberRoute,
  PartilharLanguageNumberRoute: PartilharLanguageNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
